src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date d'arrivée doit être au bon format !")
     * @Assert\GreaterThan("today", message="La date de départ doit être ultérieure à la date d'aujourd'hui.")
    */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date de départ doit être au bon format !")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doit être plus éloignée que la date d'arrivée.")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;


    /**
     * Callback appelé à chaque fois qu'on créé une réservation
     *
     * @ORM\PrePersist()
     *
     */
    public function prePersist()
    {
        if(empty($this->createdAt))
        {
            $this->createdAt = new \DateTime();
        }

        if(empty($this->amount))
        {
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }


    public function isBookableDates()
    {
        // Les jours déjà réservés
        $notAvailableDays=$this->ad->getNotAvailableDays();
        // Les jours à réserver
        $bookingDays = $this->getDays();

        $formatDay = function($day)
        {
            return $day->format('Y-m-d');
        };

        $days = array_map($formatDay, $bookingDays);
        $notAvailable = array_map($formatDay, $notAvailableDays);

        // parcours du tab $days
        foreach ($days as $day) {
            if(array_search($day, $notAvailable) !== false)
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Permet de récupérer un tableau des journées qui correspondent à ma réservation
     *
     * @return array Un tableau d'objets DateTime représentant les jours de la réservation
     */
    public function getDays()
    {
        $resultat = range(
            $this->getStartDate()->getTimestamp(),
            $this->getEndDate()->getTimestamp(),
            24*60*60
        );

        $days = array_map(function($dayTimestamp){
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingType extends ApplicationType
{
    private $transformer;

    public function __construct(FrenchToDateTimeTransformer $transformer)
    {
        $this->transformer=$transformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate', TextType::class, $this->getConfiguration("Date d'arrivée", "La date à laquelle vous comptez arriver"))
            ->add('endDate', TextType::class, $this->getConfiguration("Date de départ", "La date à laquelle vous comptez quitter les lieux"))
            ->add('comment', TextareaType::class, $this->getConfiguration(false, "Si vous avez un commentaire, n'hésitez pas à en faire part !", ['required'=>false]))
        ;

        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Form\BookingType;
use Doctrine\Common\Persistence\ObjectManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BookingController extends AbstractController
{
    private $data=array();

    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     *
     * @return Response
     */
    public function book(Ad $ad, Request $request, ObjectManager $manager)
    {
        $booking=new Booking();
        $form=$this->createForm(BookingType::class,$booking);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            $booking->setBooker($user);
            $booking->setAd($ad);

            // si date non disponible -> erreur
            if(!$booking->isBookableDates())
            {
                $this->addFlash(
                    'warning',
                    'Les dates que vous avez choisi ne peuvent pas être réservées : elles sont déjà prises.'
                );
            }else{
                // ou enregistrement
                $manager->persist($booking);
                $manager->flush();

                $this->data['id']=$booking->getId();
                $this->data['withAlert']=true;
                return $this->redirectToRoute('booking_show',$this->data);
            }
        }

        $this->data['ad']=$ad;
        $this->data['form']=$form->createView();

        return $this->render('booking/book.html.twig', $this->data);
    }

    /**
     *
     * Permet d'afficher la page d'une réservation
     *
     * @Route("/booking/{id}", name="booking_show")
     *
     * @return Response
     */
    public function show(Booking $booking)
    {
        $this->data['booking']=$booking;
        return $this->render('booking/show.html.twig', $this->data);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce : {{ ad.title }}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet"
          href="{{ asset('css/bootstrap-datepicker.min.css') }}"/>
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Réservez pour l'annonce : {{ ad.title }}</h1>
        <p>Vous êtes sur le point de réserver le bien de <strong>{{ ad.author.fullName }}</strong>, dites nous tout, on
            s'occupe du reste !</p>

        {{ form_start(form) }}

        <div class="alert alert-light">
            <h2>Commencez par nous dire quelles sont les dates qui vous intéressent</h2>
            <div class="row">
                <div class="col">
                    {{ form_row(form.startDate) }}
                </div>
                <div class="col">
                    {{ form_row(form.endDate) }}
                </div>
            </div>

            <h4 class="mt-3">Montant du séjour : <span id="amount">0</span>&euro;</h4>
            <span id="days">0</span> nuit(s) à {{ ad.price }}&euro; / nuit

            <h2>Vous avez un commentaire ?</h2>
            {{ form_row(form.comment) }}

        </div>

        <h2>Vous avez terminé !</h2>
        <p>Vacances de rêve ? Hébergement pour le boulot ? Peu importe, on est avec vous !</p>

        <button type="submit" class="btn btn-success">Je réserve !</button>

        {{ form_end(form) }}

    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('#booking_startDate, #booking_endDate').datepicker({
                format: 'dd/mm/yyyy',
                datesDisabled: [
                    {% for day in ad.notAvailableDays %}
                    "{{ day.format('d/m/Y') }}",
                    {% endfor %}
                ],
                startDate: new Date()
            });

            $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
        });
    </script>

    <script>
        function calculateAmount() {
            // Les dates recup
            const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

            if (startDate && endDate && startDate < endDate) {
                const DAY_TIME = 24 * 60 * 60 * 1000;
                const interval = endDate.getTime() - startDate.getTime();
                const days = interval / DAY_TIME;
                const amount = days *{{ ad.price }};

                $('#days').text(days);
                $('#amount').text(amount.toLocaleString('fr-FR'));
            }
        }
    </script>

{% endblock %}

templates/booking/bookings.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vos réservations passées et à venir{% endblock %}

{% block body %}

    <div class="container">
        <h1>Mes réservations</h1>
        <div class="alert alert-info mt-3">
            <p>Retrouvez ci-dessous toutes vos réservations passées et à venir</p>
        </div>

        {%  for booking in app.user.bookings %}
            {%  set ad = booking.ad %}
            <div class="row mt-5">
                <div class="col-4">
                    <img src="{{ ad.coverImage }}" alt="Photo de l'annonce {{ ad.title }}" class="img-fluid">
                </div>
                <div class="col-8">
                    <h4>{{ ad.title }}</h4>
                    <p>
                        Réservation <strong>n°{{ booking.id }}</strong><br>
                        Du {{ booking.startDate|date('d/m/Y') }} au {{ booking.endDate|date('d/m/Y') }} ({{ booking.amount }} &euro;)
                    </p>
                    <a href="{{ path('booking_show', {'id': booking.id}) }}" class="btn btn-info">Plus d'informations</a>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation n°{{ booking.id }}{% endblock %}

{% block body %}

    {% set ad = booking.ad %}
    {% set author = ad.author %}

    <div class="container">
        <h1>Votre réservation (n°{{ booking.id }})</h1>

        {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
                <h4 class="alert-heading">
                    Bravo !
                </h4>
                <p>
                    Votre réservation auprès de
                    <strong>
                        <a href="{{ path('user_read', {'slug': author.slug}) }}">
                            {{ author.fullName }}
                        </a>
                    </strong>
                     pour l'annonce
                    <strong>
                        <a href="{{ path('ads_read', {'slug': ad.slug}) }}">
                            {{ ad.title }}
                        </a>
                    </strong>
                     a bien été pris en compte !
                </p>
            </div>
        {% endif %}

        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Détails</h2>
                    <dl class="row">
                        <dt class="col-md-4">Numéro</dt>
                        <dd class="col-md-8">{{ booking.id }}</dd>

                        <dt class="col-md-4">Date d'arrivée</dt>
                        <dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>

                        <dt class="col-md-4">Date de départ</dt>
                        <dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>

                        <dt class="col-md-4">Nombre de nuits</dt>
                        <dd class="col-md-8">{{ booking.duration }}</dd>

                        <dt class="col-md-4">Montant total</dt>
                        <dd class="col-md-8">{{ booking.amount }} &euro;</dd>

                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{ booking.comment }}</dd>
                    </dl>

                    <hr>

                    <h2 class="alert-heading">Votre hôte</h2>
                    <div class="row">
                        <div class="col-3">
                            <img src="{{ author.avatar }}" class="avatar avatar-medium"
                                 alt="Avatar de {{ author.fullName }}">
                        </div>
                        <div class="col-9">
                            <h4>
                                <a href="{{ path('user_read', {'slug': author.slug}) }}">
                                    {{ author.fullName }}
                                </a>
                            </h4>
                            <span class="badge badge-primary">{{ author.ads|length }} annonces</span>
                        </div>
                    </div>
                    {{ author.description | raw }}
                    <a href="{{ path('user_read', {'slug': author.slug}) }}" class="btn btn-primary">Plus d'infos sur {{ author.firstName }}</a>
                </div>
            </div>
            <div class="col">
                <div class="alert alert-light">
                    <h2 class="alert-heading">
                        Votre hébergement
                    </h2>
                    <h4>
                        <a href="{{ path('ads_read', {'slug': ad.slug}) }}">
                            {{ ad.title }}
                        </a>
                    </h4>

                    <img src="{{ ad.coverImage }}" alt="Image de {{ ad.title }}" class="img-fluid">
                    {{ ad.content | raw }}

                    <a href="{{ path('ads_read', {'slug': ad.slug}) }}" class="btn btn-primary">
                        Plus d'informations
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}